language: node_js
sudo: false
node_js: 
    - 12
cache:
    yarn: true
    directories:
      - node_modules    
jobs:
    fast_finish: true
    install:
        - "yarn install --production=false"
    script: 
        - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    deploy: &heroku
        provider: heroku
        app: bff-marvel
        api_key: $HEROKU_AUTH_TOKEN