language: node_js
sudo: false
node_js: 
    - 12
before_install:
    - npm prune
    - npm i --global jest
install:
    - "npm install"
    - "npm install devinstall"
script:
    - "npm run test"
    - "npm uninstall devinstall"