language: node_js
sudo: false
node_js: 
    - 12
branches:
    only:
        - master
cache:
    yarn: true
    directories:
      - node_modules    
jobs:
    fast_finish: true
    install:
        - "yarn install --production=false"
    script: 
        - jest --detectOpenHandles --forceExit --coverage --coverageReporters=text-lcov | coveralls
    deploy: &heroku
        provider: heroku
        app: bff-marvel
        api_key: 3782f28f-f1b7-4180-b3b0-25580dd09552
        on:
            repo: iranjunior/api-marvel