language: node_js
sudo: false
node_js: 
    - 12
cache:
    yarn: true
    directories:
      - node_modules
before_install:
    - "yarn add -g jest"
install:
    - "yarn install --production=false"
script:
    - "yarn test"