language: node_js
sudo: false
node_js: 
    - 12
cache:
    yarn: true
    directories:
      - node_modules
before_install:
    - "yarn global add jest"
install:
    - "yarn install --production=false"
script:
    - "yarn test"